name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache npm packages
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/package-lock.json
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}

      - name: Install npm packages
        run: npm ci

      - name: Execute npm run test
        run: npm run test

      - name: Execute npm run start
        run: npm run start
